feat:first prototype of Lukasz development
asyncapi/chatbot pull request #5
Opened 2021-07-11 01:00 UTC by AceTheCreator

**Description**

- ...
- ...
- ...

**Related issue(s)**

2021-07-13 08:19 UTC, magicmatatjahu commented
@AceTheCreator Do I should make review, or it's a draft PR, but opened? If I should, please update the description of PR with list of changes.

Also, I would like to prefer to change the prefix of PR title to `chore`, not to `feat`, because probably we don't want to publish the first commit to npm :)

2021-07-13 10:17 UTC, AceTheCreator commented
> @AceTheCreator Do I should make review, or it's a draft PR, but opened? If I should, please update the description of PR with list of changes.
> 
> Also, I would like to prefer to change the prefix of PR title to `chore`, not to `feat`, because probably we don't want to publish the first commit to npm :)

Yeah you can do the review. I'd do the suggested update

2021-07-13 15:01 UTC, magicmatatjahu requested changes
First part of review. Overall awesome, but we need improve the docs, texts in questions etc :) The second part for `generatorFlow` I will try to make quick as possible, because first I need to understand it correctly.

2021-07-14 10:32 UTC, AceTheCreator commented on README.md
> +6. Server runs on `localhost:5000`
OK... I'd do that

2021-07-14 10:33 UTC, AceTheCreator commented on server/src/lib/events.js
> +events.names = eventEmitter.eventNames.bind(eventEmitter);
Awesome :+1:

2021-07-14 10:34 UTC, AceTheCreator commented on server/src/models/answers.json
> +{
OK :+1:

2021-07-14 10:35 UTC, AceTheCreator commented on server/src/models/defaultSpec.json
> +{
@magicmatatjahu what're you trying to say here?

2021-07-14 10:35 UTC, AceTheCreator commented on server/src/models/questions.js
> +        text: "what's the name of your application?",
Ok cool :+1:

2021-07-14 10:39 UTC, AceTheCreator commented on server/.babelrc
> +{
@magicmatatjahu I'm using babel because I'm making use of es6 on the server also

2021-07-14 10:39 UTC, AceTheCreator commented on server/package.json
> +  },
@magicmatatjahu Thanks for that

2021-07-14 10:40 UTC, AceTheCreator commented on server/src/models/questions.js
> +        text: 'Is this a production or development server?',
Ok :+1:

2021-07-14 10:40 UTC, magicmatatjahu commented on server/src/models/defaultSpec.json
> +{
Try to put this spec to https://playground.asyncapi.io/ and you will see the errors :)

2021-07-14 10:41 UTC, AceTheCreator commented on server/src/models/defaultSpec.json
> +{
@magicmatatjahu the info title and version comes from the users input

2021-07-15 09:10 UTC, magicmatatjahu commented on server/src/models/defaultSpec.json
> +{
Ok sorry... I thought that this spec isn't a placeholder to fill with data. It can stay :)

2021-07-15 11:48 UTC, magicmatatjahu commented on server/.babelrc
> +{
I guess, for using the EcmaScript modules?

2021-07-15 11:48 UTC, magicmatatjahu commented on server/src/services/generatorFlow.js
> +  b,
You should name the variables as `a`, `b` or something similar. To be honest, it's a hard to understand what contain these variables. Could you change to something more verbose?

2021-07-15 11:48 UTC, magicmatatjahu commented on server/src/services/generatorFlow.js
> +export default function generatorFlow(
Could you split this big function to the separate ones? I mean, to step-functions?

2021-07-15 12:05 UTC, AceTheCreator commented on server/package.json
> +  },
@magicmatatjahu I'm currently setting up the project with Lerna but I have a question. The test client folder is an interactive CLI, how am I suppose to be able to use it when using Lerna?

2021-07-15 12:17 UTC, magicmatatjahu commented on server/package.json
> +  },
Lerna should install all packages in project and then you should have one script (in root of project) to run the server and instruct how to run the cli in the separate terminal :)

2021-07-15 12:27 UTC, AceTheCreator commented on server/package.json
> +  },
@magicmatatjahu I've figured it out, thanks

2021-07-15 13:14 UTC, AceTheCreator commented on server/src/controllers/message.js
> +};
Yeah I'd keep that in mind

2021-07-15 13:24 UTC, magicmatatjahu commented on server/src/services/generatorFlow.js
> +export default function generatorFlow(
This function is very big and it's hard to read and understand, so please move some logic to separate functions - step-functions.

2021-07-26 12:35 UTC, magicmatatjahu commented on server/src/services/generatorFlow.js
> +export default function generatorFlow(
Ok, it's a POC so @AceTheCreator, you can leave as it is and fix it in the next PRs.

2021-07-26 12:36 UTC, magicmatatjahu commented on server/src/services/generatorFlow.js
> +  b,
Ok, it's a POC so @AceTheCreator, you can leave as it is and fix it in the next PRs.

2021-07-26 12:37 UTC, magicmatatjahu commented on server/package.json
> +  },
Use Lerna to install packages and leave the other things to the next PRs

2021-07-26 12:37 UTC, magicmatatjahu commented on server/.babelrc
> +{
Ok, we can leave it now, it's only a POC.

2021-07-26 12:39 UTC, magicmatatjahu commented
@AceTheCreator Could you fix the `lint` script? Please only add to the package.json the placeholder for that script like:

```json
"lint": "echo \"No linter configured yet\"",
```

Sorry for my review... 🙏🏼  It's a POC, so half of my comments could be handled in the next PRs.

2021-07-26 12:58 UTC, magicmatatjahu approved these changes
For me everything is good, except some comments, that can be handled in the next PRs. Awesome work! :)

2021-07-26 13:25 UTC, derberg commented
linter fixes will follow in next PR

2021-07-26 13:25 UTC, merged